### ISSUE TITLE
Limit amount of damage a tall post or long fence can do

### ISSUE THREAD

**Issue by pserwylo** [beat-game/beat-game#37]
Although these can end up taking up a substantial amount of area, similar to a mid sized building, they should max out the amount of damage they can do if they are only one tile wide or one tile high.

**Comment by Glitchy-Tozier** [comment]
Is this because you have stacked multiple buildings/posts on top of each other?

**Comment by pserwylo** [comment]
I think it is fair to say that this isn't really an issue per-se any more, and is better dealt with by other issues such as #67. Will close.
