### ISSUE TITLE
sparse opinions

### ISSUE THREAD

**Issue by vinniec** [beat-game/beat-game#59]
It's a nice game, it reminds me of the idea of ​​Audiosurf, I want to try to give you some ideas:
- Have you thought about using another audio format to dramatically decrease the size of the game? I suggest you take a look at the .mod format that for my ear can give a quality quite equal to that of the music you have included in very little space. For example the soundtrack of deus ex is maked with mod: https://www.youtube.com/watch?v=5BGCRQKZLhM https://www.youtube.com/watch?v=uX0hU7jQ5O4
If I remember well is also possible to slow down the track like for midi, but I'm not sure, in this case you can implement the level speed
- the game is a bit too difficult have you thought about implementing difficulty levels? super easy with no life drain,  medium with more life and higher jumps, hard like now
- You could implement a shield that repairs max 20% but recharges by earning points

**Comment by pserwylo** [comment]
Phew, so after a bit of investigating, I've gone ahead and added the shield idea. Wonderful suggestion!

https://github.com/beat-game/beat-game/releases/tag/v0.4.0 currently has a pre-release debug build that you can check out.

The shield takes damage at 5 times the normal rate (so empties quite quickly when getting hit) and recharges as you jump - recharging faster with bigger combos.

Overall, this makes the game much simpler (though we can tweak the difficulty by reducing the effectiveness of the shield - as I really like that it is quite difficult).

Regarding the music format, at this point in time I wont be doing that as a priority (although it is a good idea), beacuse the libgdx framework doesn't support such formats, so it would be a lot more work. Thanks for the suggestion though.

**Comment by vinniec** [comment]
I have tried the release and I like how you implemented it, also the progression of the levels.  Can I add a theme idea?  the character is a bird that has fallen from the nest still without feathers and is now trying to learn to fly with as high jumps as possible: p
