### ISSUE TITLE
Save record immediately after dying

### ISSUE THREAD

**Issue by Glitchy-Tozier** [beat-game/beat-game#65]
At the moment the game saves the points and distance you got only after playing the long-winded dying animation. Meaning that if you exit out of the dying-screen to restart the level quicker (or leave the game), all progress is lost.

This shouldn't happen.

So i suggest **immediately** saving the progress after dying. Makes for a less confusing user experience.

**Comment by pserwylo** [comment]
Hi @Glitchy-Tozier. Firstly, thank you so much for the detailed issue reports. It is always great to have not only a description of the issue, but a little bit of motivation about why it is important, and some quite sensible proposed solutions listed!

I completely agree with this, the information should be captured as soon as the game knows the level has ended.

**Comment by pserwylo** [comment]
This will also be addressed in the fix for #64. Will close this issues once v0.5.0 is tagged (after F-Droid builds v0.4.0).

**Comment by pserwylo** [comment]
Alright, v0.5.0 now out on F-Droid which should fix this. Thanks for your feedback.
