### ISSUE TITLE
The jumps aren't corresponding to the beats of the song or to anything.

### ISSUE THREAD

**Issue by Thewisem** [beat-game/beat-game#74]
I do understand randomly generated field but usually in rythm games the beats usually signify action but your beats aren't action at all. You just randomly jump. Its equivalent to having background music in a jumping game. It would be helpful if you could make it so that beats in the music correspond to jumping.

**Comment by pserwylo** [comment]
Thank you for the feedback @Thewisem. Unfortunately this is one of the known limitations outlined in the F-Droid description, and discussed in the #43 ("DSP and generating better levels"). As such, I'll close this for now, until we are able to come up with a better algorithm in the discussion forum. Until then, we wont be able to action the request to make the obstacles more in time with the beats.

For what it is worth, the fields are indeed generated according to the frequency information available in each given song, it just isn't as good as one would hope. For an example of a level that does a particularly good job of this, check out the 5th level "Sharply Bent Wire" (will require unlocking by earning a few achievements first). Equally, "The Courtyard" does a great job of building up shortly after the intro of the song. In that level after about 20 seconds there is a great little step up of buildings to correspond to the beginning of the main melody.

However, such examples are few and far between :(
